Added ios17 xcuitest runner
danielpaulus/go-ios pull request #347
Opened 2024-02-15 11:10 UTC by diegoperini

Added support for xcuitests on iOS 17

2024-02-15 19:49 UTC, danielpaulus approved these changes

2024-02-15 19:51 UTC, danielpaulus requested changes
seems like the ci is failing with some missing files @diegoperini

2024-02-19 11:38 UTC, diegoperini commented
> seems like the ci is failing with some missing files @diegoperini

Done 👍

2024-02-20 06:46 UTC, danielpaulus approved these changes
LGTM

2024-02-20 11:25 UTC, merged