feat: add RSD instrumentation service support
danielpaulus/go-ios pull request #396
Opened 2024-04-09 13:21 UTC by michal-przytarski

2024-04-12 11:01 UTC, dmissmann requested changes
Great, they moved those things as they are to `dtservicehub` 🙂

2024-04-12 13:02 UTC, michal-przytarski commented on ios/listdevices.go
> +func (device *DeviceEntry) SupportsRsd() bool {
done :D [22ba1b1](https://github.com/danielpaulus/go-ios/pull/396/commits/22ba1b15953b5be15652be61723f8ccd4d23a6ed)

2024-04-12 13:02 UTC, michal-przytarski commented on ios/instruments/helper.go
> +	if device.SupportsRsd() {
done :D [5dfc702](https://github.com/danielpaulus/go-ios/pull/396/commits/5dfc7023f78fc0598c272b0e2c6739a7dfa8bdf9)

2024-04-15 07:43 UTC, dmissmann approved these changes
thanks! 🙇‍♂️

2024-06-06 08:23 UTC, michal-przytarski commented
Hi
What should we do with this PR? Pretty much all the changes are already merged. Only refactor left.
Do you want to merge it, or should I close it?

2024-06-07 10:26 UTC, dmissmann commented
> Do you want to merge it, or should I close it?

I would still merge it, but I can't. It says `This branch is out-of-date with the base branch` on my end and I assume that just means that you have to merge `main` into your branch, or rebase onto `main`

2024-06-10 20:12 UTC, merged